language: php

notifications:
  email: false
  slack:
    secure: TPla4YTyILAY8W0aCWQsUezP0T1XQ2EFFR+tv5L1u8W2zeGltAROgLnAZM8juzwy6xpsDeBB57b8wxYOhZTnvPkd8PmoKXs7/w9qST6g1wlIldCWkkbvjkxr4ALJthnRitrJoe3KjV2fqUA91x0Fez6d5nBeGM6C43PiIurb2H0=

php:
  - 7.0

install: composer install -o

after_script:
  - wget https://scrutinizer-ci.com/ocular.phar
  - php ocular.phar code-coverage:upload --format=php-clover build/logs/clover.xml

after_success:
  - bash <(curl -s https://codecov.io/bash)
