language: php

notifications:
  email: false
  slack:
    secure: TPla4YTyILAY8W0aCWQsUezP0T1XQ2EFFR+tv5L1u8W2zeGltAROgLnAZM8juzwy6xpsDeBB57b8wxYOhZTnvPkd8PmoKXs7/w9qST6g1wlIldCWkkbvjkxr4ALJthnRitrJoe3KjV2fqUA91x0Fez6d5nBeGM6C43PiIurb2H0=

php:
  - 5.4
  - 5.5
  - 5.6

install: composer install -o

before_script:
  - mysql -e 'create database myapp_test;'

after_script:
  - wget https://scrutinizer-ci.com/ocular.phar
  - php ocular.phar code-coverage:upload --format=php-clover build/logs/clover.xml
